### ISSUE TITLE
OpenCv2 empty frame on UNIX OS

### ISSUE THREAD

**Issue by augusto196** [SmartRoomCorporation/SmartRoom#1]
when executing  Main.py in FaceRecon module I have noticed this error:

File "Main.py", line 40, in <module>
    small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)
cv2.error: OpenCV(4.4.0) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-xyb5iebi/opencv/modules/imgproc/src/resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

it seems that webcam is not recognized by the system (Mac OS Catalina version: 10.15.6)

**Comment by MatteoBosco89** [comment]
Fixed with this [commit](https://github.com/SmartRoomCorporation/SmartRoom/commit/2159491a9c9416728676b75a2ab37fb9bdfebd46)

**Comment by MatteoBosco89** [comment]
On Mac OS systems, when webcam is loaded with OpenCV, it skips 3-4 frames before the library can actally access to frames. The value returned was None and system crash. Now while OpenCV wait for access, it will display a loading image and the system doesn't crash
